### ISSUE TITLE
Migrate to toml

### ISSUE THREAD

**Issue by EriKWDev** [alacritty/alacritty-theme#38]
Alacritty is in the process of migrating the configuration from yaml to toml.

You get a warning on recent versions if you're using the yaml config file format.

`alacritty migrate` automatically translates the yaml config to toml config and could probably be used to translate the themes here as well.

Maybe both a yaml and toml version could be kept here in the meantime? It feels like it would not be too hard to automatically translate between them using a script

**Comment by chrisduerr** [comment]
We will migrate to toml as soon as a new version is released.

**Comment by laneme** [comment]
In the meantime, just convert the theme file using some yaml to toml converter.

Theme files are in https://github.com/alacritty/alacritty-theme/blob/master/themes/
They're single files with some colors. I just pasted mine directly in `alacritty.toml`

![image](https://github.com/alacritty/alacritty-theme/assets/26094878/a8f9402f-5427-4e37-975d-188a15fdab69)

Otherwise, Import syntax should be like this, i suppose
```toml
import = [".config/alacritty/themes/themes/citylights.toml"]
```

**Comment by chrisduerr** [comment]
> In the meantime, just convert the theme file using some yaml to toml converter.

Alacritty can migrate from yaml to toml using `alacritty migrate`.

**Comment by craigmac** [comment]
@laneme after trying to out, I've discovered that there is no import/include mechanism for TOML, so the standard "include your theme" advice will no longer work

**Comment by cypher8773** [comment]
> @laneme after trying to out, I've discovered that there is no import/include mechanism for TOML, so the standard "include your theme" advice will no longer work

Thanks for your information

**Comment by randuck-dev** [comment]
As far as I can tell this is a breaking change, right? I just installed latest stable version of alacritty (v0.12.3) and then cloned this repo for the themes. However, that would not work, since the commit that moves everything to .toml files has been made. As a workaround I am just calling `git checkout 808b81b2e88884e8eca5d951b89f54983fa6c237`, after a clone of the repository, in order to use a version that still has the .yaml files. 
Could we tag the latest version that still supports the .yaml file types so that it would be possible to do `git clone -b TAG_HERE https://github.com/alacritty/alacritty-theme`. 

The reason I ask is that I have fully automated my dotfiles setup, and in that case it would be cleaner if I can checkout on the tag instead of cloning and then cd'ing into the repo in order to perform the correct checkout.

**Comment by chrisduerr** [comment]
> As far as I can tell this is a breaking change, right?

Yes.

> Could we tag the latest version that still supports the .yaml file types so that it would be possible to do git clone -b TAG_HERE https://github.com/alacritty/alacritty-theme.

Sure: https://github.com/alacritty/alacritty-theme/tree/yaml

**Comment by randuck-dev** [comment]
> > As far as I can tell this is a breaking change, right?
> 
> Yes.
> 
> > Could we tag the latest version that still supports the .yaml file types so that it would be possible to do git clone -b TAG_HERE https://github.com/alacritty/alacritty-theme.
> 
> Sure: https://github.com/alacritty/alacritty-theme/tree/yaml

Appreciate the fast response and thanks for the tagging!
