### ISSUE TITLE
not everyone is on 0.13+ release yet - make themes backwards compatible

### ISSUE THREAD

**Issue by vtrenton** [alacritty/alacritty-theme#60]
Why completely remove the yml examples and files? 0.13 is still a new branch (the latest release is literally 0.13.0 as of writing this) Pop_OS! for example ships with 0.12.2 in its repos.

https://github.com/alacritty/alacritty-theme/commit/11664caf4c2bfae94e006e860042f93b217fc0f7

For anyone wondering how to get it working with older releases:

```bash
# Start with the regular instructions
mkdir -p ~/.config/alacritty/themes
git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes

# Reset the gitrepo to a release that contained the yaml files
cd ~/.config/alacritty/themes/
git reset --hard yaml
```

Then in your `alacritty.yml` add:
```yaml
import:
 - ~/.config/alacritty/themes/themes/{theme}.yaml
```

Obviously this should go without saying these yaml files are unmaintained so they wont be up-to-date with what's on the page

**Comment by chrisduerr** [comment]
Learn how git works, old themes aren't lost only because master doesn't have them anymore.

https://github.com/alacritty/alacritty-theme/tree/yaml

**Comment by chrisduerr** [comment]
I did read your comment, but if you know how git works, it's not an issue. So if you think this is an issue, you clearly need to learn how git works.

**Comment by Tejeev** [comment]
> Learn how git works, old themes aren't lost only because master doesn't have them anymore.
> 
> https://github.com/alacritty/alacritty-theme/tree/yaml

vtrenton made a legitimate request (which any product manager worth their grit would attest to since it affects user experience and costs you nothing except humility and character.  It's not constructive to respond derisively.  The software industry benefits from good documentation and the support of those still earlier in the learning curve than you are. Your derision was uncalled for and reflects badly on Alacrity, though I'm sure that doesn't concern you.. Still, you've made a potentially embarrassing assumption regarding his skill at tasks he's clearly familiar with but too humble to argue the particulars about while just being a nice guy and helping the community out.
