### ISSUE TITLE
Add Theme Rose Pine 

### ISSUE THREAD

**Issue by lucianovictor** [alacritty/alacritty-theme#8]
Adding new theme Rose Pine and variants [https://github.com/rose-pine/alacritty]

**Comment by chrisduerr** [comment]
Adding new themes is fairly simple and should be well documented in the readme. If you're interested in having a theme supported, you should try adding it yourself.

Since everyone can easily add themes themselves, it doesn't make sense to add themes based on issue request. It causes unnecessary work for maintainers and indicates that nobody is even interested enough to throw up a PR to do it.
